### ISSUE TITLE
Linux Compatibility Issue

### ISSUE THREAD

**Issue by AustinHaugerud** [Hopson97/Minecraft-Tutorial#1]
I know that you develop on Windows, but from what I can tell there shouldn't be anything in your code, library choices, etc. prohibiting the program from building and executing on Linux. I cloned your project and converted from a Codeblocks Project to a CMake project (something possibly worth looking into since CMake makes it much easier to distribute to various platforms). I got it to build fine, but for some reason the program acts completely spazzy. I believe the expected behaviour of your program currently  is a single textured cube that you can view smoothly. The cube currently appears but it spins around for some reason.  The camera seems to be working. I have no idea currently why this happens, or if perhaps I missed something and this is expected right now. If this is an actual issue, I can help you bug hunt.

**Comment by Hopson97** [comment]
i think I know why

https://github.com/Hopson97/Minecraft-Tutorial/blob/master/Source/States/Playing.cpp#L32

Remove this line of code and it will no longer be spinning :)

**Comment by AustinHaugerud** [comment]
That fixed it, looks like what's supposed to happen as in the video. On a side note, your program is Linux compatible fully it seems, in case you didn't already know. Like I said, you may want to consider distributing with CMake, I (among some others, though I can't give a metric) don't care for Codeblocks. In stead of forcing someone to install codeblocks you could let people use CMake and generate to Visual Studio, Codeblocks, Makefile, etc.
