### ISSUE TITLE
yt link in readme seems to be dead

### ISSUE THREAD

**Issue by jonathansty** [Hopson97/Minecraft-Tutorial#2]
The youtube link in README.md to the playlist seems to be dead.

**Comment by Hopson97** [comment]
https://www.youtube.com/playlist?list=PLMZ_9w2XRxiZq1vfw1lrpCMRDufe2MKV_

**Comment by Hopson97** [comment]
wtf

**Comment by Hopson97** [comment]
I think it is the underscore

**Comment by Hopson97** [comment]
https://goo.gl/VBPdtN

**Comment by Hopson97** [comment]
Sweet this works
